### ISSUE TITLE
【機能要望】拡張MIBの追加機能

### ISSUE THREAD

**Issue by knt-n** [twsnmp/twsnmpfc#10]
任意の拡張MIBの追加登録機能が欲しい

**Comment by twsnmp** [comment]
気がつくのが遅くてすみません。
拡張MIBの追加する機能はあります。
Web画面からは追加できないので、マニュアルに書くのを忘れてました。
データストアのフォルダにextmibsというフォルダを作成して、そこにMIBファイル
https://github.com/twsnmp/twsnmpfc/blob/main/conf/mib.txt
のような形式を追加すれば、読み込むはずです。
試してみたらnoteに書きます。

**Comment by twsnmp** [comment]
https://github.com/twsnmp/twsnmpfc/commit/afce08bbfdd6eaaa41ecc18fe2afe2ea6925448b
で修正しました。

**Comment by twsnmp** [comment]
v1.12.1で対応版をリリースしました。

**Comment by knt-n** [comment]
対応ありがとうございました
