### ISSUE TITLE
TWSNMP設定について

### ISSUE THREAD

**Issue by katuhiko-watanabe** [twsnmp/twsnmpfc#11]
ご質問先が間違っているかもしれませんが、失礼いたします。
TWSNMP-FCを使用し監視を行いたいです。
linuxサーバをSNMPを使用してプロセス監視を実施したいのですが、
モード、パラメータ、判定スクリプトの設定方法がわかりません。
お忙しいところ恐縮ですが、ご教授お願い致します。

現在、設定としては
モード:get
パラーメータ:hrSWRunName.1540
判定スクリプト:設定なし
結果:プロセス名は見えています

以上、よろしくお願いいたします。

**Comment by twsnmp** [comment]
テンプレートから選択して、フィルターにプロセス名を設定すればよいです。
![image](https://user-images.githubusercontent.com/5225950/189015216-e0fba6d5-3684-45d5-ab0a-c3a60f4e30f4.png)

**Comment by twsnmp** [comment]
モード:count
パラーメータ:hrSWRunName
フィルター：プロセス名
判定スクリプト:count > 0

**Comment by katuhiko-watanabe** [comment]
早速のご回答ありがとうございます。
ご教授頂きました対応にて確認が取れました。
ありがとうございました。
