### ISSUE TITLE
プロセス起動数監視時の動作について

### ISSUE THREAD

**Issue by katuhiko-watanabe** [twsnmp/twsnmpfc#12]
お世話になっております。

度々申し訳ございません。ご質問させてください。
linuxサーバのプロセス監視をSNMPにて実施しておりますが、
プロセスSNMP自体が停止した場合、プロセス監視自体が
request timeoutになってしまい、状態が「不明」になります。

状態を「不明」ではなく、「異常」にすることは可能でしょうか。
判定スクリプトなどでrequest timeoutの場合は不明ではなく、
他の状態変化として扱うことは可能でしょうか。

または「不明」の場合も障害として通知対象にする事は可能でしょうか。

以上、よろしくお願いいたします。

**Comment by twsnmp** [comment]
> 状態を「不明」ではなく、「異常」にすることは可能でしょうか。
> 判定スクリプトなどでrequest timeoutの場合は不明ではなく、
> 他の状態変化として扱うことは可能でしょうか。
> 
これはできない。


> または「不明」の場合も障害として通知対象にする事は可能でしょうか。
> 

これもできない。


SNMPで取得できない場合に、異常と判断するポーリングモードを追加しようと思います。

**Comment by katuhiko-watanabe** [comment]
ありがとうございました。
対応のご検討をお願いいたします。

以上、よろしくお願いいたします。

**Comment by twsnmp** [comment]
https://github.com/twsnmp/twsnmpfc/issues/13
で対応します。
