### ISSUE TITLE
イベントログの状態と表記がずれている？

### ISSUE THREAD

**Issue by mitaniMaru** [twsnmp/twsnmpfc#19]
またまたお世話になります。
引き続き絶賛監視中で助かっております。

各ノードのログなのですが、ステータスとイベント表記がずれているような？
![image](https://user-images.githubusercontent.com/116621465/213947512-9aa30cb3-d681-4d82-9d9f-e19a6010d4c2.png)

状態：軽度　のイベントの表記はlow
状態：復帰　のイベントの表記はrepair

なのかなーと。
まぁ慣れたらどっちでも良いのですが。

**Comment by twsnmp** [comment]
ちょっと、わかりにくいのですが、ずれているのではありません。
状態のほうは、現在（ログ記録時点）の状態で、イベントの末尾の英語の状態は以前の状態です。
復帰時に通知する時の判断に使っている値です。
今後、表示しないようにするかもしれません。

**Comment by mitaniMaru** [comment]
なるほど
了解しました！
