### ISSUE TITLE
WOLの設定

### ISSUE THREAD

**Issue by mitaniMaru** [twsnmp/twsnmpfc#20]
お世話になっております。

今更TWSNMP FCでもWOLが使えるとの記事を見て、さっそく試してみようかと思ったのですが、
WOLのメニューが表示されません。
もひとつ言うと、MACアドレスを登録・編集するメニューも見当たらないです。

なにか設定が必要でしょうか？

環境はDocker版の1.18です。

**Comment by twsnmp** [comment]
ノードの右クリックメニューにWOLがありますが、
WOLのメニューは、MACアドレスが空欄のノードでは表示されません。
今のバージョンだとMACアドレスは自動入力しかありません。
ARP監視か、twpcapセンサーからのログから自動入力します。
MACアドレスを手動で入れられるように、次のバージョンで対応しようと思います。

**Comment by twsnmp** [comment]
「レポート」ー「デバイス分析」ー「LAN」
のリストからMACアドレスを自動入力します。

**Comment by mitaniMaru** [comment]
ご回答ありがとうございます。
どうもSynologyのNASに搭載されているDockerでは標準ネットワーク接続がbridgeの為、Win版のDockerと同じくARP監視がうまく動かないようです。
host接続というものにすると無事WOLのメニューが表示できたので、どっかのタイミングでネットワーク接続を移行しようと思います。
ありがとうございました！

**Comment by mitaniMaru** [comment]
https://kb.synology.com/ja-jp/DSM/help/Docker/docker_network?version=7
