### ISSUE TITLE
ポーリング設定/VMware/Datastore のデータストア名が有効にならない

### ISSUE THREAD

**Issue by radi-sh** [twsnmp/twsnmpfc#22]
ポーリング設定で「種別」：「VMware」、「モード」：「Datastore」を選択したとき、「フィルター」部分に「データストア名」を入力するようになっていますが、実際には「抽出」部分にデータストア名を入力しないと有効に機能しません。

**Comment by twsnmp** [comment]
ありがとうございます。
本来、「フィルター」に入力するのが正解ですが、内部的にフィルターではなくパラメータでフィルターしていました。
ポーリングのテンプレートでは「フィルター」になっていました。
VMWare関連のポーリングはすべて、同じ間違いがあります。
既に使っている人ことを考えて
（１）フィルター欄に設定したものを使う
（２）フィルター欄が空欄でパラメータ欄に設定があれば、そちらを使う
にします。
パラメータ欄が空欄でも全データストアの使用量でポーリングするので気づかなかったバグです。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/6f3b4ad9-78b1-440a-a072-1193a50ba0ef)

この設定ですね

**Comment by radi-sh** [comment]
早速のご対応ありがとうございます。
既に使っている人への配慮もありがとうございます。
現在はWindows版のみ使用していますので次回のリリースで確認させていただきます。
