### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by asheroto** [twsnmp/twsnmpfc#23]
This text was translated at translate.google.com.

Hello!

I found this program while browsing Chocolatey's community repository. It looks great. I think many people in the English-speaking world would be interested in this software. :-)

Unfortunately I don't speak Japanese.

For my projects that require localization, I have used https://gitlocalize.com and had great success with it. It's free.

Another good option is https://crowdin.com but it has a limit of 60k words for free, or a paid plan with more words.

ChatGPT can be used to help translate the strings. GitLocalize also has "Machine Translation" that can perform such tasks.

Thanks!
asheroto
---
このテキストはtranslate.google.comで翻訳されました。

こんにちは！

Chocolatey のコミュニティ リポジトリを閲覧しているときにこのプログラムを見つけました。 見た目も素晴らしいです。 英語圏の多くの人がこのソフトウェアに興味を持っていると思います。😊

残念ながら私は日本語を話せません。

ローカリゼーションが必要なプロジェクトでは、https://gitlocalize.com を使用し、大きな成功を収めました。 それは無料です。

もう 1 つの良いオプションは https://crowdin.com ですが、無料では 60,000 単語までの制限があり、より多くの単語を含む有料プランもあります。

ChatGPT は文字列の翻訳に役立ちます。 GitLocalize には、このようなタスクを実行できる「機械翻訳」もあります。

ありがとう！
アシェロト

**Comment by twsnmp** [comment]
Thank you.
We have no plans to support this project in English.
The old TWSNMP that is available on Chocolatey will also not be English-enabled.
We plan to support the new twsnmpfk we are developing now in English.

ありがとうございます。
このプロジェクトを英語対応する予定はありません。
Chocolateyで公開している古いTWSNMPも英語対応する予定はありません。
今開発している新しいtwsnmpfkを英語対応する予定です。

**Comment by twsnmp** [comment]
The TWSNMP we are developing now is
https://github.com/twsnmp/twsnmpfk

I use DeepL for translation.
https://www.deepl.com/ja/translator
