### ISSUE TITLE
[要望]ログのExcel出力の際に、日時の表示フォーマットを整えて欲しい

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#24]
Syslog,Trapログ,イベントログをExcelに吐き出した際の日時体系が揃っていません。
TrapとSyslogの日時フォーマットはmm:ss.0ですが、これをyyyy/mm/dd hh:mm:ss.000に出来ないでしょうか。
eventログの日時フォーマットはyyyy/mm/dd h:mmですが、これをyyyy/mm/dd hh:mm:ss.000に出来ないでしょうか。

**Comment by sadayoshi-git** [comment]
追加要望ですが、SyslogをExcel保存した場合の名称がSysogになっているのをSyslogにしてもらえませんか?

**Comment by twsnmp** [comment]
> SyslogをExcel保存した場合の名称がSysogになっているのをSyslogにしてもらえませんか?

ありがとうございます。確認したので修正します。

**Comment by twsnmp** [comment]
タイムスタンプは確認します。

**Comment by twsnmp** [comment]
タイムスタンプは、基本的に画面に表示された文字列を、そのまま出力しています。
CSVで出力しているものと同じです。
Excelで読み込むと自動で日時データに変換して自動でフォーマットして表示しているようです。
書式を変えれば、表示が変わります。
Excelの仕様なので、これはこのままにしようと思います。
CSVは、＝”のような、特殊なフォーマットなので、エスケープ処理しない出力にも対応しようと思います。

**Comment by sadayoshi-git** [comment]
> Excelで読み込むと自動で日時データに変換して自動でフォーマットして表示しているようです。
> 書式を変えれば、表示が変わります。
> Excelの仕様なので、これはこのままにしようと思います。

承知しました。
ファイル名の修正が終わったらcloseして下さい。

**Comment by sadayoshi-git** [comment]
すみません。誤ってclose入れてしまったので、開きなおします。
