### ISSUE TITLE
[要望]シスログ表示においてIPだけではなくノード名相も載せてもらえないでしょうか。

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#25]
Syslogにおいて、ホスト名欄にはIPだけ入っていますが、ノード一覧にあるIPは名称も載せて欲しい。(trapログと同様に)

**Comment by twsnmp** [comment]
受信したsyslogのフォーマットが正しければ、syslog内のホスト名がはいります。

![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/c3f9899a-efc8-45ce-bc2e-b383bc750873)

syslogからホスト名を取得できない場合にIPアドレスになります。
IPになった時に登録したノード名に変換できるか検討します。

**Comment by twsnmp** [comment]
検索する時に、ホスト名がIPアドレスの場合には、ホスト名を登録ノードとDNSで検索するするように
します。

**Comment by twsnmp** [comment]
DNSの検索は、表示が遅くなりそうなのでやめます。
登録ノード名を検索します。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/7eb42bea-2642-44d0-8b7f-527b647601a4)

**Comment by sadayoshi-git** [comment]
確認出来ました。
