### ISSUE TITLE
[要望]syslog受信したIPを、自動でセンサーと認識しないように出来ないでしょうか。

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#26]
現状、syslog受信した対象は自動でセンサーとして認識されてしまうようですが、ロギングの頻度が少ない機器のログを受信する場合、通知頻度が少ない為に障害と認識されてメールが飛んでしまいます。
あらかじめセンサーと認識されたものだけセンサーと認識する事は出来ないでしょうか。

**Comment by twsnmp** [comment]
> 現状、syslog受信した対象は自動でセンサーとして認識されてしまうようですが、ロギングの頻度が少ない機器のログを受信する場合、通知頻度が少ない為に障害と認識されてメールが飛んでしまいます。

この問題は、以前、認識して、監視しないボタンをつけた記憶があります。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/8ccdf1a0-5bf0-42de-8db7-b73513cd6378)

右端のボタンです。
押せば、停止になって、もう一度押せば、戻ります。

今試してみたら、設定を保存できないかもしれないので、確認します。

**Comment by sadayoshi-git** [comment]
停止ボタンの存在は認識しているのですが、時間経過で復活してしまいます。
記録していないので、どのタイミングで復活するのかは正確には分かっていませんが、一か月に1回は復活するはずです。

**Comment by twsnmp** [comment]
> 停止ボタンの存在は認識しているのですが、時間経過で復活してしまいます。
の動作を修正しようと思います。

**Comment by twsnmp** [comment]
停止ボタンの状態が復活する原因は、DBに保存されないためでした。
保存する時に、前回の保存時刻からから変化のあったものだけ保存する仕様になっていますが、
停止するのは、受信がないものなので保存対象にならないの状態でした。

**Comment by twsnmp** [comment]
消えていたのは、再起動後だと思います。
修正して停止状態を維持できるようになりました。
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/a1b4be7f-1c07-42d6-84e5-0ca6aad6fb87)

**Comment by sadayoshi-git** [comment]
ありがとうございました。
