### ISSUE TITLE
[要望]ログの検索範囲の時刻設定をテキスト入力可能に出来ないでしょうか

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#27]
検索範囲の時刻指定ですが、反応がシビアで00:00を指定したくてもいつも操作がずれて00:01とかになってしまいます。
テキスト入力も可能にできないでしょうか。

また、検索範囲開始時刻の既定値は00:00のようですが、検索範囲終了時刻の既定値は23:59のようですね。
しかし、これだと24時間のデータをする場合に23:59:00から23:59:59.999のデータが漏れてしまう為、いつも翌日の0:00を指定しています。
終了時刻の既定値を23:59:59.999あるいは0:00に出来ないでしょうか。
もっとも、この件については賛否両論あるようにも思われます。ご検討下さい。

**Comment by twsnmp** [comment]
このコントロールは、私も気に入っていないので、何か考えます。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/15cf44c8-3924-4d10-a075-99b5699937bd)

テキスト入力にします。

**Comment by twsnmp** [comment]
時刻範囲の入力を簡易にする方法を思いついたので組み込んでみます。

**Comment by twsnmp** [comment]
![2023-11-17_18-03-27 (1)](https://github.com/twsnmp/twsnmpfc/assets/5225950/a554ca85-b1c7-450a-a315-0e54c4277540)
いい感じになったと思います。

**Comment by sadayoshi-git** [comment]
ありがとうございました。
