### ISSUE TITLE
[要望]ログ検索条件のノード指定対象をソートしてもらえませんでしょうか

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#28]
ログ検索条件指定時のノード選択は、現状ノード選択になっていますけれど、

1. ソートされていない為対象を探すのが大変です。ソートして頂けませんか。
2. テキスト入力で、例えば頭文字入力でドロップダウンの選択対象ノードにジャンプしてくれると非常に助かります。

**Comment by twsnmp** [comment]
他でも使っているautocompleteが使えると思うので検討します。

**Comment by twsnmp** [comment]
Autocompleteにしました。
![2023-11-18_05-58-59 (1)](https://github.com/twsnmp/twsnmpfc/assets/5225950/bdb9eeb7-df8f-4d4d-afac-0b5aea44f51e)

**Comment by sadayoshi-git** [comment]
ありがとうございました。
