### ISSUE TITLE
[要望]データストア保存ボタンを、定期保存ボタンと即時保存の2つにしてもらえませんでしょうか

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#29]
データ保存ですが、たとえば最新版適用などの際には即時バックアップした上でバージョンアップ作業を行うと思います。
この場合、
1. 定期バックアップを即時バックアップに変更してバックアップ
2. バージョンアップなどの作業
3. あらためて定期バックアップを設定
という手順が必要になりますが、定期バックアップと並列に即時バックアップボタンがあればバックアップ設定を都度変更する必要がなくなります。

**Comment by twsnmp** [comment]
考えます。

**Comment by twsnmp** [comment]
バックアップの選択肢に
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/e908bfae-d5bd-4afc-a096-95c5fb8b602e)
を追加します。
１回実行したら毎日AM3:00に自動的に設定変更します。

**Comment by sadayoshi-git** [comment]
ありがとうございました。
