### ISSUE TITLE
[質問]twsnmpに比べ通知頻度が減っていますが、通知までの間に障害が解消した場合の通知はどうなりますか?

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#30]
twsnmpと比べてメール通知が少ない事は非常にありがたく思っております。
しかしながら、体感的に、既に障害が解消していても障害メールが届くような気がしています。
仕様として、障害解消した場合メールは飛ばないようになっているのでしょうか？

もっとも、メールが飛んでから私がメール確認するまでの間に障害が解消しているのかもしれないのですが。

**Comment by twsnmp** [comment]
通知は、指定した期間の間のログで判断しています。
期間内に障害のログがあれば、現在復帰していても、通知は送信されます。
復帰通知も送信する設定になっていれば、両方送信されます。

**Comment by sadayoshi-git** [comment]
理解しました。有難うございました。
