### ISSUE TITLE
[障害]influxdb連携設定時、influxdbに接続出来ない場合にログイン画面すら表示されない

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#31]
次のようなエラーがずっとロギングされ、twsnmpfcのログイン画面が表示されないという症状になりました。
2023-11-16T09:06:50.006 send polling log to influxdb1 err=Post "http://localhost:8086/write?consistency=&db=mydb&precision=s&rp=": 

根本的な原因はinfluxdbにあるようでgrafanaからも繋がりません。それは別件なのでよいのですが、twsnmpfcのその他の機能は使いたいものです。画面が起動しないのでinfluxdb設定を無効にする事も出来ません。
対応出来ませんでしょうか。

暫定措置で、influxdb連携を無効にするオプション追加とかでも構いません。

**Comment by twsnmp** [comment]
> 次のようなエラーがずっとロギングされ、twsnmpfcのログイン画面が表示されないという症状になりました。

influxdbへ接続できない時の処理に問題があるようです。
私の環境ではログインできない状態にはなりませんが、設定を正常に接続できる状態に戻しても
エラーが出続けるようです。

確認して修正します。

**Comment by sadayoshi-git** [comment]
追加情報です。

influxdbおよびgrafanaはwsl2上のdockerにてコンテナ生成しています。
twsnmpfcをwsl2上のコンテナにするとうまくudp受信出来ない為、twsnmpfcだけはデスクトップアプリを使用しています。

influxdbとの通信不具合についてですが、その後windowsの再起動で直ってしまいました。wsl2のネットワーク周りで何か不具合が起きているのかもしれません。

そして、復旧後の動作検証では問題は出ませんでした。
twsnmpfc起動時にinfluxdbが存在しない場合。twsnmpfc起動後にinfluxdbが存在しなくなった場合。どちらも。

この際のエラーメッセージは、当初と異なり以下のようになりました。
**2023-11-16T09:06:50.006 send polling log to influxdb1 err=Post "http://localhost:8086/write?consistency=&db=mydb&precision=s&rp=":**

twsnmpfcの不具合ではないようです。もう10日ほど状況調査致しますが、それで新しい情報が無ければcloseしたいと思います。
お騒がせ致し、申し訳ございません。

**Comment by twsnmp** [comment]
多くのポーリングのデータをinfluxdbへ送信している場合に、デットロックのような状態が発生するかもしれません。
ポーリングのログを送信する時に、同時に２つの送信が起動しないように排他制御しています。
これが蓄積してご指摘の現象が発生するのかもしれません。

**Comment by twsnmp** [comment]
1. Influxdbの設定時の接続チェックでエラーの場合に以後の書き込み処理を動作させないようにする
2. 書き込みのタイムアウトを5秒から１秒にする

の対策をしてみます。

**Comment by twsnmp** [comment]
とりあえず
4ac6abd6452c466d30f9567a1fced0c7f69b7745
で修正

**Comment by sadayoshi-git** [comment]
influxdbとの通信不具合、再発しません。
修正頂いた内容が効果的だったのかもしれませんし、私の環境が壊れていただけかもしれません。
いずれにしろ、クローズ致します。
