### ISSUE TITLE
組み込み済みのMIBファイルが古いものがある

### ISSUE THREAD

**Issue by knt-n** [twsnmp/twsnmpfc#35]
組み込み済みのMIBファイルの定義が古いものがある (下記 MIB で発見)

TWSNMP FC v1.34.0(9284cd7) で確認

*  IANAifType-MIB 該当箇所 (履歴を見る限り 2000 年3月6日版以降に追加されたと思われる)
[![IANAifType-MIB 該当箇所](https://github.com/twsnmp/twsnmpfc/assets/38205211/c81158c9-5965-4c32-8603-85bdb10e17a5)](https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib)

* 表示
![SnapCrab_NoName_2024-2-6_11-11-46_No-00](https://github.com/twsnmp/twsnmpfc/assets/38205211/a201b319-7f92-435c-b553-943074e8a5ca)

**Comment by twsnmp** [comment]
ありがとうございます。
前から気になっていましたが、原因がわかりました。
IANAifType-MIB.txtは、組み込んでいましたが、
MIBファイルを読み込む順番に問題がありました。
この後に、RFC1213-MIB.txt（MIB1）を読み込んでいるので定義が上書きされてました。

**Comment by twsnmp** [comment]
順番を変えると
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/b3b79172-e1c0-4106-a185-59c7cf26d312)
のようになりました。

**Comment by knt-n** [comment]
対応ありがとうございます
v1.35.0(84d1c15) で正常に表示されることを確認しました
