### ISSUE TITLE
各状態の件数サマリ表示機能が欲しいです。

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#36]
ノードメニューとポーリングメニューにおいて、状態が重度のもの、あるいは軽度のもの、ついでに復帰のものが出ていないかを表示出来ませんでしょうか。
メニュー上部に、メニュー表示時の各状態の件数サマリが表示されれば十分です。
stateのフィルタ機能を使う場合、stateを数回変更するのは意外と手間です。

**Comment by twsnmp** [comment]
> stateのフィルタ機能を使う場合、stateを数回変更するのは意外と手間です。

そうですね、次のリリース時、stateのフィルターに「正常以外」をつけようと思います。

**Comment by twsnmp** [comment]
TWSNMP FKで対応している以下の方法にしようと思います。

- ノードなどの状態別のソートを数値化して行い、重度、軽度、注意、復帰、正常、その他の順になるようにする
- 状態のフィルターを重度、軽度以上、注意以上、復帰以上、すべて　にする

**Comment by sadayoshi-git** [comment]
ありがたいです

**Comment by twsnmp** [comment]
状態のソート順とフィルターの動作を改善しました。次のリリースをお楽しみに
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/8a0282a5-c2db-4df1-99d6-97626d274789)

**Comment by twsnmp** [comment]
v1.36.1で対応しました。

**Comment by twsnmp** [comment]
とりあえず、クローズします。
