### ISSUE TITLE
RasberryPI上で起動する、Ubuntu22.04環境でTWSNMPが

### ISSUE THREAD

**Issue by hoge2501** [twsnmp/twsnmpfc#38]
![error](https://github.com/twsnmp/twsnmpfc/assets/95415857/ae00107b-1008-4291-8f70-a77a42c7576b)

Rasberrypi上のUbuntu22.04を使用して起動しようとすると、添付のようなエラーとなり起動できません。
同じようにDockser環境で起動もできませんでした。。。。
何が原因か全くわからない状態です。せめてヒントだけでもいただけると幸いです。

**Comment by twsnmp** [comment]
このエラーログは、TWSNMP FCではないようみえます。
どのようにインストールしましたか？

**Comment by twsnmp** [comment]
https://note.com/twsnmp/n/nbee48380227b
を見てインストールしたのかと思いますが、
これは、TWSNMP FCではありません。
すでに、開発中止している復刻（失敗）版です。

**Comment by twsnmp** [comment]
TWSNMP FCは、
https://note.com/twsnmp/n/nc6e49c284afb?magazine_key=meed0d0ddab5e
のLinux版のインストールをみてください。

**Comment by hoge2501** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/95415857/0133f212-9cc4-471c-b68b-38758b7271ec)

実施してみました。どうやら、gpgキーがlegacy（古い？）といわれてしまっています。
Windowsでは無事起動しましたが、Rasberrypi4＋Ubuntu22.04環境下では、起動しないようです。
環境依存というのはありますでしょうか。

**Comment by twsnmp** [comment]
出ている１つ目はエラーはapt-keyが使えなくなるという
https://yassi.hatenablog.com/entry/2021/03/26/071644
だと思います。
これは、たぶん警告なので、問題ないと思います。
問題は、２つ目なのですが、arm64版がないというエラーです。
twsnnmp fcのaptパッケージは、amd64とarm(32bit)版しか配布していません。
なので、Raspberry Piの３２ビットOSで試すか、apt以外の方法でインストールする必要があります。

**Comment by twsnmp** [comment]
apt以外のインストール方法としては
（１）Docker版をインストールする
（２）debパッケージをダウンロードしてインストールする
の２つがあります。

**Comment by twsnmp** [comment]
> （２）debパッケージをダウンロードしてインストールする

失礼しました。ARM６４ビット版のdebパッケージは配布していませんでした。
Docker版はARM64がありました。

**Comment by twsnmp** [comment]
添付のファイルをダウンロードして解凍すれば、LinuxのARM64版の実行ファイルになります。

[twsnmpfc_linux_arm64.zip](https://github.com/twsnmp/twsnmpfc/files/14717856/twsnmpfc_linux_arm64.zip)

**Comment by hoge2501** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/95415857/6899fedf-73e6-4010-a860-88ef68058291)
zipファイル作っていただきありがとうございました。
実行したところ、先ほどのエラーは出なくなり起動できるところまでは実行できたのではないかと思っています。
が、twsnmpの初期DB構築時に、エラーが出てしまい起動ができない状態です。

>twsnnmp fcのaptパッケージは、amd64とarm(32bit)版しか配布していません
後一緒に教えてください。twsnmpのDockerパッケージですが実行した際にDockerのビルド環境に差分があるといわれ実行できませんでした。確か自身の環境が「arm64/(何か/)v8」といわれDockerのビルド環境と違いますというエラーだったかと思います。そうなると、現状において一番の現実解は「Raspberry Piの３２ビットOS」で起動するものとなりますでしょうか。
お手数おかけいたしますが、教えていただけると幸いです。

**Comment by twsnmp** [comment]
ZIPのARM６４版のエラーは、datastoreというディレクトリがないためだと思います。
datastoreというディレクトリを作成するか、別のディレクトリを起動パラメータで指定して
起動してみてください。

https://note.com/twsnmp/n/nc6e49c284afb?magazine_key=meed0d0ddab5e
の

**Linux/Mac OS/Windowsでのコマンドラインからの起動方法**

が参考になると思います。

**Comment by twsnmp** [comment]
今後のリリースでLinuxのARM64版にも対応しようと思います。

**Comment by hoge2501** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/95415857/d1ff1d80-ca30-4b61-86be-d7d28ec4599d)
無事起動しました(泣)。数時間に渡りお時間いただき、誠に申し訳ございませんでした。
CCNPおよCCIEの課題にNetflowがありそのために勉強する環境が欲しく、必死でした。
いただく回答も、技術屋として背筋が伸びる思いで見ていました。40歳を超えた自分ですが、その文字をみて背筋がシュっとした思いです。合格に向けて、これから検証します。重ね重ねとなりますが、本当にありがとうございました。

**Comment by hoge2501** [comment]
> 今後のリリースでLinuxのARM64版にも対応しようと思います。

それは本当にうれしいです。アプリ側の人のその起点の利かせ方が本当に勉強になります。
リリース楽しみにしています。

**Comment by hoge2501** [comment]
> > 今後のリリースでLinuxのARM64版にも対応しようと思います。
> 
> それは本当にうれしいです。アプリ側の方の起点の利かせ方が本当に勉強になります。 リリース楽しみにしています。

**Comment by twsnmp** [comment]
起動できて何よりです。
こちらもARM６４版が起動できない情報がいただけて助かりました。
ありがとうございます。

**Comment by twsnmp** [comment]
> twsnmpのDockerパッケージですが実行した際にDockerのビルド環境に差分があるといわれ実行できませんでした。確か自身の環境が「arm64/(何か/)v8」といわれDockerのビルド環境と違いますというエラーだったかと思います。

https://note.com/twsnmp/n/nc6e49c284afb
に説明を追加しました。

Dockerのイメージをtwsnmp/twsnmpfcを指定するとamd64のイメージを実行しようとします。
たぶん
twsnmp/twsnmpfc:arm64_v1.36.1
のように、ARM６４のタグをつけて起動すれば、できると思います。

**Comment by twsnmp** [comment]
ARM64版もAPTのリポジトリに含めました。

**Comment by hoge2501** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/95415857/40636296-8f1a-4c21-acb9-d54e2eee4638)

DockerImage作っていただきありがとうございました。指定した通りに実行し無事起動し、ログインできることまで確認いたしました。

**Comment by twsnmp** [comment]
使えて、何よりです。
このチケットはクローズします。
