### ISSUE TITLE
1.36.0からメール通知が出来なくなりました

### ISSUE THREAD

**Issue by h-araki000** [twsnmp/twsnmpfc#39]
素晴らしいソフトの公開ありがとうございます。利用させて頂いております。
1.36.1にアップデートした後、メール通知が出来なくなりました。
1.35.0に戻すとメール通知が出来ます。

メール送信時にキャプチャすると
Client Helloの後、メールサーバからAlert (Level: Fatal, Description: Handshake Failure)が返ってきて通信が終了します。
1.35.0の場合は、Server Helloが返ってきて通信が続きます。
1.35.0と1.36.1を比較するとCipher Suites が19 から14に減っていました。
こちらのメールサーバはTLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c) を採用するようで、
1.36.1では存在しないため終了してしまうようです。
Cipher Suitesの種類を戻して頂けないでしょうか？

**Comment by h-araki000** [comment]
windows版です。

**Comment by twsnmp** [comment]
>  1.35.0と1.36.1を比較するとCipher Suites が19 から14に減っていました。
> こちらのメールサーバはTLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c) を採用するようで、
> 1.36.1では存在しないため終了してしまうようです。
> Cipher Suitesの種類を戻して頂けないでしょうか？
> 

TWSNMP FCのソースコードで明示的にCipher Suitesを設定していません。
GO言語のtlsパッケージのデフォルト設定を使用しています。
GO言語のバージョンを更新したことが影響しているようです。

５ヶ月前に、
TLS_RSA_WITH_AES_128_GCM_SHA256
は、デフォルトから外れて、
InsecureCipherSuitesのリスト移動したようです。

この影響だと思います。

**Comment by twsnmp** [comment]
https://github.com/golang/go/blame/master/src/crypto/tls/cipher_suites.go
の
CipherSuites()
と
InsecureCipherSuites()
です。

**Comment by twsnmp** [comment]
GO言語のバージョンを戻すのは良くないので、
InsecureCipherSuites
も含めるオプション設定を追加する方向で考えます。

**Comment by h-araki000** [comment]
メールサーバはレンタルなので簡単に対処できないのでオプション設定の追加よろしくお願いします。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/1254fc7a-936e-4118-9ebd-b07c743a030d)
のようなスイッチ付けてONにすれば、

TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384

の２つを追加するようにしました。

**Comment by twsnmp** [comment]
正式リリース前に対応したバージョンの実行ファイルを添付します。　試せるようならお願いします。
[twsnmpfc_win.zip](https://github.com/twsnmp/twsnmpfc/files/15030546/twsnmpfc_win.zip)

**Comment by h-araki000** [comment]
オプション追加ありがとうございます。
終日外出となりますので今日は試せそうにありません。申し訳ないです。

**Comment by twsnmp** [comment]
テストして頂き、ありがとうございます。
次のリリースに含めます。
このチケットはクローズしておきます。
