### ISSUE TITLE
netflow受信ができない

### ISSUE THREAD

**Issue by OTM2021** [twsnmp/twsnmpfc#4]
CiscoとFotiGateからNetFlow V9のパケットをtwsnmpに投げているのですが
ログ情報を見ると何も表示されないようです。
netstatでポートが開放は確認しパケットキャプチャでudp-2055で
NetFlow V9のパケットの着信は確認しております。

使用OSはWindows Server2016 R2でパーソナルファイアウォールは無効化しております。

**Comment by twsnmp** [comment]
NetFlowのV9には対応していません。
V5かV10(IPFIX)を試してみてください。

**Comment by OTM2021** [comment]
なるほど、回答ありがとうございます。
