### ISSUE TITLE
[要望]ノードリストからMIBブラウザーを開けるようにしてほしい

### ISSUE THREAD

**Issue by radi-sh** [twsnmp/twsnmpfc#41]
現在、MIBブラウザーを開くためにいちいちマップ画面に戻って、目的のノードを探して右クリックメニューから開かないといけないので結構手間です。
ノードリストに並んでいる操作ボタンの中からMIBブラウザーが開ければかなり操作性がよくなると思います。

**Comment by twsnmp** [comment]
ありがとうございます。
ノードリストの操作ボタンにMIBブラウザーがないことに、今気づきました。
追加します。

**Comment by twsnmp** [comment]
![image](https://github.com/twsnmp/twsnmpfc/assets/5225950/68042307-ce21-49ec-8b2a-7b4ebc333767)
追加しました

**Comment by radi-sh** [comment]
ご対応ありがとうございます。

**Comment by radi-sh** [comment]
快適に操作できるようになりました。
