### ISSUE TITLE
【質問】誤ったパスワードを入力してしまった場合の再ログインの方法を教えてください

### ISSUE THREAD

**Issue by TAKUMA-Enami** [twsnmp/twsnmpfc#42]
お世話になります。
大変初歩的な質問で申し訳ありませんが、
・前回まで正しいユーザーID（twsnmp）/パスワード（twsnmp）で
　ログインできていた
・今回、誤ったユーザーID（TWSNMP）/パスワード（TWSNMP）で　
　ログインしてしまい、
　再度正しいユーザーID（twsnmp）/パスワード（twsnmp）で
　ログインしようとしても、ログインできない
という状態になっています。
対処方法をご教示いただけますと幸いです。

**Comment by twsnmp** [comment]
パスワードを間違えてもログインできない状態にはならないと思います。
考えられるのは、
（１）TWSNMP　FCが停止している（ブラウザーだけ動作している）
（２）ブラウザーが間違ったパスワードを自動入力している
などです。

とりあえず、ブラウザーで再読み込み（リロード）してしてみてください。
原因が（１）なら画面が表示されないと思います。

**Comment by TAKUMA-Enami** [comment]
お世話になります。
お手間を取らせて申し訳ありません。
・TWSNMP FCが起動していることは確認しています。
 　TWSNMP FCが起動でも状態は「稼働」になっています
　ブラウザーの再読み込みをするとログイン画面の最初の状態に戻ります
・ブラウザーの過去履歴、パスワード関連を全て削除して実行しましたが、
　ログインできません。
　Edge、Googl Chromeの双方で試しましたが、両方ともログインできません
・TWSNMP FCを一度アンインストールしてPCを再起動し、
　再度TWSNMP FCをインストールし直しましたが、
　改善しません。

**Comment by twsnmp** [comment]
パスワードを変更していませんか？
外部からだれかがアクセスしてパスワードを変更したとか？

データストアのフォルダーを新規のフォルダーに変更して起動すれば、
初期パスワードに戻ると思います。
これでログインできますか？

**Comment by TAKUMA-Enami** [comment]
データストアのフォルダーを新規のフォルダーに変更して起動し、
無事ログイン出来ました。
本方法は憶えておきます。

ご対応いただき、ありがとうございました。
本件はClose頂いてOKです。

**Comment by twsnmp** [comment]
ログインできて何よりです。
パスワード忘れた時のために、コマンドラインからの起動でパスワードリセットする
仕組みをつけようと思います。
