### ISSUE TITLE
[要望]ログインページ、ようこそページのレイアウト変更について

### ISSUE THREAD

**Issue by sadayoshi-git** [twsnmp/twsnmpfc#43]
私は主にPC上のブラウザからこちらのソフトを利用しているのですが、ログイン画面のバージョン情報に多くのリンクが含まれている為、毎回ボタンにフォーカスするまでにtabキーを沢山叩く必要があります。これはようこそ画面でも同様です。
バージョン情報をボタンより下部に配置して頂ければボタンにたどり着くまでのキー押下を減らせるのですが如何でしょうか。
非常に我儘なお願いである為、恐縮ですが。

**Comment by twsnmp** [comment]
試せる場所に戻ったら確認してみます。タブオーダー変更で改善できる気がします。

**Comment by twsnmp** [comment]
動作を確認しました。
デフォルトのボタンをtabオーダーの最初になるように
tabindex="1" を追加すれば、tabキー1回でボタンが選択状態になりました。
この方法で対応します。

**Comment by twsnmp** [comment]
ログイン画面など他も、同じような対策をしておきます。

**Comment by twsnmp** [comment]
実は、右上のアイコン・ボタンが、＜ログイン＞ボタンと同じでした。
現状のバージョンでも、このボタンは、tabキー１回で選択されます。お試しください。
![image](https://github.com/user-attachments/assets/fd0028df-0ff8-4284-9482-4b9ae3702523)

**Comment by sadayoshi-git** [comment]
ありがとうございます。

**Comment by twsnmp** [comment]
v1.43.0で対応しました。

**Comment by twsnmp** [comment]
対応したので、Closeします。
