### ISSUE TITLE
IPドメインとマスク情報を取得するネットワークインターフェースの選択ができるようにしていただけますか

### ISSUE THREAD

**Issue by forest20146** [twsnmp/twsnmpfc#44]
仮想スイッチを含めFlagUpの複数のインターフェースがある場合に使用するインターフェースを選択できるようにするか、IPドメインとマスクを手動で設定できるようにしてください。arpwatch/makeLoacalCheckAddrsで対象のIPドメインとマスクを取得する際に条件に合致する最後のifsを使用するようになっているようで正しい情報が取得できない場合があります。

**Comment by twsnmp** [comment]
ありがとうございます。
ご指摘の通り複数インターフェイスの時に問題のある実装になっていました。
対策します。

**Comment by twsnmp** [comment]
管理したいIPアドレスの範囲は指定できたほうがよいので設定できるように変更します。
設定できる範囲をインターフェイスのリストから取得して表示できるようにします。
自動発見の＜自動IP範囲＞ボタンのようにします。

**Comment by forest20146** [comment]
迅速な対応ありがとうございます。自動IP範囲ボタンと同様のUIということは手動で設定の変更が可能という理解でよろしいでしょうか。私のサイトの特殊事情でVLANで接続した複数サイトを同一IPドメインとするためにインターフェースには/18を、監視対象となる各サイト内は/24ないし/27を使用していますので手動で設定できる余地を残していただけると助かります。別途MAC固定ノードの扱いで問題があったので別イシューで報告させていただきます。

**Comment by twsnmp** [comment]
今朝、もう少し検討して

> 自動発見の＜自動IP範囲＞ボタンのようにします。

は止めました。

ARP監視するIPアドレスの範囲を設定可能にしました。

![image](https://github.com/user-attachments/assets/74833ba7-c7f0-49c1-a091-94e897013e76)

初期値または、空欄で保存した場合に、LANインターフェイスのアドレスから範囲を
自動設定します。
複数インターフェイスの場合は、重複しないアドレス範囲をカンマ区切りのCIDRで登録します。
CIDRの他に、192.168.1.1-192.168.1.30の形式でカンマ区切りで登録できるようにします。

イベントログも範囲単位で使用率を記録します。

**Comment by forest20146** [comment]
対応ありがとうございます。本件をクローズします。
