### ISSUE TITLE
MACアドレス固定ノードのMACアドレスが書き換えられてしまうことがあります

### ISSUE THREAD

**Issue by forest20146** [twsnmp/twsnmpfc#45]
MACアドレス固定ノードがオフライン中に同一IPが別のデバイスに割り当てられると、MACアドレス固定ノードのMACアドレスが書き換えられてしまうことがあります。logger/arpwatchのcheckFixMACNodeでarpTableをIPで検索して得られるMACアドレスでノード設定を更新しているために起きていると思われます。あわせてノード設定のUIにMACアドレスの項目を追加してください。

**Comment by twsnmp** [comment]
変更するのはcheckFixMACNodeの関数ではないかもしれません。
IPアドレスレポートの処理でノードのMACアドレスを書き換える部分あるので、その影響かもしれません。
MACアドレスは、UIで編集可能にします。
空欄で保存すると再取得できるようにしたいと思います。

**Comment by twsnmp** [comment]
ノードのMACアドレスを編集可能にしました。

![image](https://github.com/user-attachments/assets/ab1127a7-90fb-454f-a3f8-22c0271bf013)

**Comment by twsnmp** [comment]
空欄で保存すると自動で取得します。

**Comment by forest20146** [comment]
対応ありがとうございます。GOは使ったことがないのでそこまで見渡せず、arpwatch/checkFixMACModeでmacToIPTableに該当するMACがなければnodeのIPをクリアするコードを入れてビルドしていました。お手数かけました。本件クローズします
