### ISSUE TITLE
通知設定でメールパスワードを入力しても保存されない

### ISSUE THREAD

**Issue by sigumani** [twsnmp/twsnmpfc#46]
使い方の問題かもしれませんがDiscord通知とメール通知を併用しようと考えパスワードを入力して保存ボタンを押したところパスワード欄が空欄になっておりました。
設定上問題ないと思いわざと障害を起こしてテストを行ったところDiscord通知は正しく行われておりますが、メール通知は行われませんでした。
この状況でメール通知テストを行ったところテストメッセージの送信に失敗しましたと表示されております。

試しにパスワードを入力してメール通知テストが問題ないことを確認してから保存を押したところ空欄になり、
再度メール通知テストを行ったところテストメッセージの送信に失敗しましたと表示されてメールが送信されていないことを確認しております。

**Comment by sigumani** [comment]
環境を書き忘れておりました。
OS:Ubuntu 24.04.01 LTS
となります。

**Comment by twsnmp** [comment]
ありがとうございます。
現象を確認しました。

**Comment by twsnmp** [comment]
バグかとおもいましたが、ソースコードをみると仕様でした。
パスワードは、
（１）表示する時は空欄にする
（２）保存する時に空欄ならば変更しない
という仕様です。
テスト時には、パスワードをもう一度いれてください。

**Comment by sigumani** [comment]
ご確認ありがとうございます。
仕様ということであれば問題ございません

またメール通知についてもメーラー側の問題で受信できておらずTWSNMP側からは送信ができておりました。

大変お騒がせして申し訳ありませんでした
